# -*- coding: utf-8 -*-
"""YoutubeAPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o1zl6W_pmbezFsJfKRSSWbwThUciH8Ow
"""

#import libraries
import requests
import pandas as pd
import time

#KEYS
API_KEY = #INCLUDE API_KEY FROM YOUTUBE HERE
CHANNEL_ID = "UCKHhA5hN2UohhFDfNXB_cvQ"

def get_video_details(video_id):
      
      #COLLECTION VIEWS, LIKES AND COMMENTS
      url_video_stats = "https://www.googleapis.com/youtube/v3/videos?id="+video_id+"&part=statistics&key="+API_KEY
      response_video_stats = requests.get(url_video_stats).json()

      view_count = response_video_stats['items'][0]['statistics']['viewCount']
      like_count = response_video_stats['items'][0]['statistics']['likeCount']
      comment_count = response_video_stats['items'][0]['statistics']['commentCount']

      return view_count, like_count, comment_count

def get_videos(df):
  #MAKE API CALL
  pageToken = ""
  url = "https://www.googleapis.com/youtube/v3/search?key="+API_KEY+"&channelId="+CHANNEL_ID+"&part=snippet,id&order=date&maxResults=10000"+pageToken

  response = requests.get(url).json()
  time.sleep(1)

  for video in response['items']:
    if video['id']['kind'] == 'youtube#video':
      video_id = video['id']['videoId']
      video_title = video['snippet']['title']
      upload_date = video['snippet']['publishedAt']
      upload_date = str(upload_date).split("T")[0]

      view_count, like_count, comment_count = get_video_details(video_id)

      #SAVE THE DATA IN PANDAS DATAFRAME

      df = df.append({
          'video_id':video_id,'video_title':video_title,
          'upload_date':upload_date,'view_count':view_count,
          'like_count':like_count, 'comment_count':comment_count},ignore_index=True)
      
  return df

#MAIN PROCESS

#BUILDING DATAFRAME
df = pd.DataFrame(columns=["video_id","video_title","upload_date","view_count","like_count","comment_count"])

df = get_videos(df)

df

